/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AppCatalogAppResourcesValue {
    Application(Box<models::Application>),
    Bucket(Box<models::Bucket>),
    Certificate(Box<models::Certificate>),
    Secret(Box<models::Secret>),
    Topic(Box<models::Topic>),
    Vhost(Box<models::Vhost>),
    Volume(Box<models::Volume>),
}

impl Default for AppCatalogAppResourcesValue {
    fn default() -> Self {
        Self::Application(Default::default())
    }
}
