/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppCatalogApp {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "manifestUrn")]
    pub manifest_urn: String,
    /// child resources
    #[serde(rename = "resources")]
    pub resources: std::collections::HashMap<String, models::AppCatalogAppResourcesValue>,
}

impl AppCatalogApp {
    pub fn new(name: String, manifest_urn: String, resources: std::collections::HashMap<String, models::AppCatalogAppResourcesValue>) -> AppCatalogApp {
        AppCatalogApp {
            name,
            configuration: None,
            manifest_urn,
            resources,
        }
    }
}

