/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationVolumes {
    /// the full name of the volume that needs to be mounted in the container.
    #[serde(rename = "name")]
    pub name: String,
}

impl ApplicationVolumes {
    pub fn new(name: String) -> ApplicationVolumes {
        ApplicationVolumes {
            name,
        }
    }
}

