/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketWatchStatus {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<models::BucketWatch>>,
    #[serde(rename = "actual", skip_serializing_if = "Option::is_none")]
    pub actual: Option<Box<models::BucketWatch>>,
    #[serde(rename = "status")]
    pub status: Box<models::AllocationStatus>,
}

impl BucketWatchStatus {
    pub fn new(status: models::AllocationStatus) -> BucketWatchStatus {
        BucketWatchStatus {
            configuration: None,
            actual: None,
            status: Box::new(status),
        }
    }
}
