/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketWatch {
    #[serde(rename = "bucket")]
    pub bucket: String,
}

impl BucketWatch {
    pub fn new(bucket: String) -> BucketWatch {
        BucketWatch { bucket }
    }
}
