/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketAccessConfiguration {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "bucket")]
    pub bucket: String,
    #[serde(rename = "readable")]
    pub readable: bool,
    #[serde(rename = "writable")]
    pub writable: bool,
}

impl BucketAccessConfiguration {
    pub fn new(name: String, bucket: String, readable: bool, writable: bool) -> BucketAccessConfiguration {
        BucketAccessConfiguration {
            name,
            bucket,
            readable,
            writable,
        }
    }
}

