/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketAccess {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "bucket")]
    pub bucket: String,
    #[serde(rename = "readable")]
    pub readable: bool,
    #[serde(rename = "writable")]
    pub writable: bool,
    #[serde(rename = "credentialidentifierref")]
    pub credentialidentifierref: String,
    #[serde(rename = "credentialsecretref")]
    pub credentialsecretref: String,
}

impl BucketAccess {
    pub fn new(
        name: String,
        bucket: String,
        readable: bool,
        writable: bool,
        credentialidentifierref: String,
        credentialsecretref: String,
    ) -> BucketAccess {
        BucketAccess {
            name,
            bucket,
            readable,
            writable,
            credentialidentifierref,
            credentialsecretref,
        }
    }
}
