/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataCatalogAsset {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl DataCatalogAsset {
    pub fn new(kind: String, name: String) -> DataCatalogAsset {
        DataCatalogAsset {
            kind,
            name,
        }
    }
}

