/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlinkJobManager {
    /// CPU quota for the Flink job manager (minimum 0.3 = 30% of 1 CPU)
    #[serde(rename = "cpus")]
    pub cpus: f64,
    /// Memory (MB) for this Flink job manager (minimum 1024 = 1 GB)
    #[serde(rename = "mem")]
    pub mem: i32,
}

impl FlinkJobManager {
    pub fn new(cpus: f64, mem: i32) -> FlinkJobManager {
        FlinkJobManager {
            cpus,
            mem,
        }
    }
}

