/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitValueCpuAllOf {
    /// The number of CPUs to provision for the managed tenant (factions of a vCPU core, 1.0 equals 1 vCPU)
    #[serde(rename = "value")]
    pub value: f64,
}

impl LimitValueCpuAllOf {
    pub fn new(value: f64) -> LimitValueCpuAllOf {
        LimitValueCpuAllOf { value }
    }
}
