/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedTenantServices {
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl ManagedTenantServices {
    pub fn new(name: Name, enabled: bool) -> ManagedTenantServices {
        ManagedTenantServices { name, enabled }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "vpn")]
    Vpn,
    #[serde(rename = "tracing")]
    Tracing,
    #[serde(rename = "monitoring")]
    Monitoring,
}

impl Default for Name {
    fn default() -> Name {
        Self::Vpn
    }
}
