/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Notification {
    /// true if the notification has to do with removal of the allocation, false if it relates to creation/update of the resource
    #[serde(rename = "remove")]
    pub remove: bool,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<std::collections::HashMap<String, String>>,
}

impl Notification {
    pub fn new(remove: bool, message: String) -> Notification {
        Notification {
            remove,
            message,
            args: None,
        }
    }
}
