/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThirdPartyBucketConcessionConfiguration {
    /// your name for this bucket owned by a third party
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "shareidentifier")]
    pub shareidentifier: String,
}

impl ThirdPartyBucketConcessionConfiguration {
    pub fn new(name: String, shareidentifier: String) -> ThirdPartyBucketConcessionConfiguration {
        ThirdPartyBucketConcessionConfiguration {
            name,
            shareidentifier,
        }
    }
}

