/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThirdPartyBucketConcessionRegistration {
    /// the name you give to the third party bucket you are registering
    #[serde(rename = "name")]
    pub name: String,
    /// provided to you by the third party
    #[serde(rename = "shareidentifier")]
    pub shareidentifier: String,
    /// plaintext credential identifier provided to you by the third party
    #[serde(rename = "credentialidentifierplaintext")]
    pub credentialidentifierplaintext: String,
    /// plaintext secret value provided to you by the third party
    #[serde(rename = "credentialsecretplaintext")]
    pub credentialsecretplaintext: String,
}

impl ThirdPartyBucketConcessionRegistration {
    pub fn new(
        name: String,
        shareidentifier: String,
        credentialidentifierplaintext: String,
        credentialsecretplaintext: String,
    ) -> ThirdPartyBucketConcessionRegistration {
        ThirdPartyBucketConcessionRegistration {
            name,
            shareidentifier,
            credentialidentifierplaintext,
            credentialsecretplaintext,
        }
    }
}
