/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.7.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vhost {
    #[serde(rename = "value")]
    pub value: String,
}

impl Vhost {
    pub fn new(value: String) -> Vhost {
        Vhost { value }
    }
}
