/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vhost {
    #[serde(rename = "value")]
    pub value: String,
}

impl Vhost {
    pub fn new(value: String) -> Vhost {
        Vhost { value }
    }
}
