components:
  schemas:
    AllocationStatus:
      type: object
      properties:
        derivedFrom:
          description: >
            pointer to the parent allocation or limit that caused this allocation
            to be implicitly created
          type: string
        provisioned:
          description: indicates whether configuration and actual state match
          type: boolean
        notifications:
          type: array
          items:
            $ref: "#/components/schemas/Notification"
      required: [ provisioned, notifications ]
    ChildList:
      type: array
      items:
        type: string
    Notification:
      type: object
      properties:
        remove:
          type: boolean
          description: true if the notification has to do with removal of the allocation, false if it relates to creation/update of the resource
        message:
          type: string
        args:
          type: object
          additionalProperties:
            type: string
      required: [ remove, message ]

  responses:
    200-AllocationStatus:
      description: status of the allocation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AllocationStatus'
          example:
            derivedFrom: "optional URN of optional parent allocation"
            provisioned: true
            notifications: []
    200-ChildList:
      description: returns a list of ids representing child resources of the requested resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChildList'
