name: Publish DSH SDK

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
    - uses: actions/checkout@v6
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo check -p dsh_sdk
    - run: cargo build -p dsh_sdk
    - run: cargo test -p dsh_sdk --all-features --  --test-threads=1
    - run: cargo publish -p dsh_sdk
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
  